# Setup
title: "The Missing Semesters of Your CS"
description: "Practical tech skills for RUET students — Linux, Git, Debugging, and more."
baseurl: "/missing-semester"
url: "https://missing-semesters-ruet.github.io/"
author: "The Missing Semesters of your CS @ RUET"

# Settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
permalink: /:title/
future: true
# safe: true # breaks local rendering if enabled
timezone: Asia/Dhaka
analytics:
  tracking_id: G-P7WVHD84D1

collections:
  "2019":
    output: true
  "2020":
    output: true
  "2025":
    output: true

# Excludes
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
